CREATE SCHEMA IF NOT EXISTS `SPOTIFY`;

CREATE TABLE IF NOT EXISTS `ARTISTS`
(
    `ID`            BIGINT(20)      NOT NULL AUTO_INCREMENT,
    `NAME`          VARCHAR(512)    NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `ALBUMS`
(
    `ID`            BIGINT(20)      NOT NULL AUTO_INCREMENT,
    `NAME`          VARCHAR(512)    NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `SONGS`
(
    `ID`            BIGINT(20)      NOT NULL AUTO_INCREMENT,
    `NAME`          VARCHAR(512)    NOT NULL,
    `ARTIST_ID`     BIGINT(20)      NULL DEFAULT NULL,
    `ALBUM_ID`      BIGINT(20)      NULL DEFAULT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_SONGS_ARTISTS`
        FOREIGN KEY (ARTIST_ID) REFERENCES `ARTISTS` (ID),
    CONSTRAINT `FK_SONGS_ALBUMS`
        FOREIGN KEY (ALBUM_ID) REFERENCES `ALBUMS` (ID)
);